enum EErrorCode {
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INVALID_TOKEN_ERROR = 'INVALID_TOKEN_ERROR',
    ACCESS_DENIED_ERROR = 'ACCESS_DENIED_ERROR',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    RESOURCE_NOT_FOUND_ERROR = 'RESOURCE_NOT_FOUND_ERROR',
    DATABASE_CONNECTION_ERROR = 'DATABASE_CONNECTION_ERROR',
    UNAUTHENTICATED_USER_ERROR = 'UNAUTHENTICATED_USER_ERROR',
}

export default EErrorCode;